// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/daryakovzhun/collect-metrics/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIAgent is a mock of IAgent interface.
type MockIAgent struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentMockRecorder
}

// MockIAgentMockRecorder is the mock recorder for MockIAgent.
type MockIAgentMockRecorder struct {
	mock *MockIAgent
}

// NewMockIAgent creates a new mock instance.
func NewMockIAgent(ctrl *gomock.Controller) *MockIAgent {
	mock := &MockIAgent{ctrl: ctrl}
	mock.recorder = &MockIAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgent) EXPECT() *MockIAgentMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockIAgent) Collect(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Collect", ctx)
}

// Collect indicates an expected call of Collect.
func (mr *MockIAgentMockRecorder) Collect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockIAgent)(nil).Collect), ctx)
}

// GetAllMetrics mocks base method.
func (m *MockIAgent) GetAllMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockIAgentMockRecorder) GetAllMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockIAgent)(nil).GetAllMetrics))
}

// GetCounterMetrics mocks base method.
func (m *MockIAgent) GetCounterMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounterMetrics indicates an expected call of GetCounterMetrics.
func (mr *MockIAgentMockRecorder) GetCounterMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterMetrics", reflect.TypeOf((*MockIAgent)(nil).GetCounterMetrics))
}

// GetGaugeMetrics mocks base method.
func (m *MockIAgent) GetGaugeMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGaugeMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGaugeMetrics indicates an expected call of GetGaugeMetrics.
func (mr *MockIAgentMockRecorder) GetGaugeMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGaugeMetrics", reflect.TypeOf((*MockIAgent)(nil).GetGaugeMetrics))
}

// GetMetricByID mocks base method.
func (m *MockIAgent) GetMetricByID(metric *models.Metrics) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricByID", metric)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricByID indicates an expected call of GetMetricByID.
func (mr *MockIAgentMockRecorder) GetMetricByID(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricByID", reflect.TypeOf((*MockIAgent)(nil).GetMetricByID), metric)
}

// SetCounterMetric mocks base method.
func (m *MockIAgent) SetCounterMetric(metric *models.Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCounterMetric", metric)
}

// SetCounterMetric indicates an expected call of SetCounterMetric.
func (mr *MockIAgentMockRecorder) SetCounterMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCounterMetric", reflect.TypeOf((*MockIAgent)(nil).SetCounterMetric), metric)
}

// SetGaugeMetric mocks base method.
func (m *MockIAgent) SetGaugeMetric(metric *models.Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGaugeMetric", metric)
}

// SetGaugeMetric indicates an expected call of SetGaugeMetric.
func (mr *MockIAgentMockRecorder) SetGaugeMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGaugeMetric", reflect.TypeOf((*MockIAgent)(nil).SetGaugeMetric), metric)
}
