// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/daryakovzhun/collect-metrics/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIServerController is a mock of IServerController interface.
type MockIServerController struct {
	ctrl     *gomock.Controller
	recorder *MockIServerControllerMockRecorder
}

// MockIServerControllerMockRecorder is the mock recorder for MockIServerController.
type MockIServerControllerMockRecorder struct {
	mock *MockIServerController
}

// NewMockIServerController creates a new mock instance.
func NewMockIServerController(ctrl *gomock.Controller) *MockIServerController {
	mock := &MockIServerController{ctrl: ctrl}
	mock.recorder = &MockIServerControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServerController) EXPECT() *MockIServerControllerMockRecorder {
	return m.recorder
}

// GetAllMetrics mocks base method.
func (m *MockIServerController) GetAllMetrics(ctx context.Context) ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics", ctx)
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockIServerControllerMockRecorder) GetAllMetrics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockIServerController)(nil).GetAllMetrics), ctx)
}

// GetMetric mocks base method.
func (m *MockIServerController) GetMetric(ctx context.Context, metric *models.Metrics) (models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", ctx, metric)
	ret0, _ := ret[0].(models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockIServerControllerMockRecorder) GetMetric(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockIServerController)(nil).GetMetric), ctx, metric)
}

// Ping mocks base method.
func (m *MockIServerController) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockIServerControllerMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIServerController)(nil).Ping), ctx)
}

// SetMetric mocks base method.
func (m *MockIServerController) SetMetric(ctx context.Context, metric *models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetric", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMetric indicates an expected call of SetMetric.
func (mr *MockIServerControllerMockRecorder) SetMetric(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetric", reflect.TypeOf((*MockIServerController)(nil).SetMetric), ctx, metric)
}

// UpdateMetrics mocks base method.
func (m *MockIServerController) UpdateMetrics(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetrics", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetrics indicates an expected call of UpdateMetrics.
func (mr *MockIServerControllerMockRecorder) UpdateMetrics(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetrics", reflect.TypeOf((*MockIServerController)(nil).UpdateMetrics), ctx, metrics)
}

// MockIAgentController is a mock of IAgentController interface.
type MockIAgentController struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentControllerMockRecorder
}

// MockIAgentControllerMockRecorder is the mock recorder for MockIAgentController.
type MockIAgentControllerMockRecorder struct {
	mock *MockIAgentController
}

// NewMockIAgentController creates a new mock instance.
func NewMockIAgentController(ctrl *gomock.Controller) *MockIAgentController {
	mock := &MockIAgentController{ctrl: ctrl}
	mock.recorder = &MockIAgentControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgentController) EXPECT() *MockIAgentControllerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockIAgentController) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockIAgentControllerMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIAgentController)(nil).Start), ctx)
}
