// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/daryakovzhun/collect-metrics/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetAllMetrics mocks base method.
func (m *MockIRepository) GetAllMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockIRepositoryMockRecorder) GetAllMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockIRepository)(nil).GetAllMetrics))
}

// GetCounterMetrics mocks base method.
func (m *MockIRepository) GetCounterMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounterMetrics indicates an expected call of GetCounterMetrics.
func (mr *MockIRepositoryMockRecorder) GetCounterMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterMetrics", reflect.TypeOf((*MockIRepository)(nil).GetCounterMetrics))
}

// GetGaugeMetrics mocks base method.
func (m *MockIRepository) GetGaugeMetrics() ([]models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGaugeMetrics")
	ret0, _ := ret[0].([]models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGaugeMetrics indicates an expected call of GetGaugeMetrics.
func (mr *MockIRepositoryMockRecorder) GetGaugeMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGaugeMetrics", reflect.TypeOf((*MockIRepository)(nil).GetGaugeMetrics))
}

// GetMetricByID mocks base method.
func (m *MockIRepository) GetMetricByID(metric models.Metrics) (models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricByID", metric)
	ret0, _ := ret[0].(models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricByID indicates an expected call of GetMetricByID.
func (mr *MockIRepositoryMockRecorder) GetMetricByID(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricByID", reflect.TypeOf((*MockIRepository)(nil).GetMetricByID), metric)
}

// SetCounterMetric mocks base method.
func (m *MockIRepository) SetCounterMetric(metric models.Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCounterMetric", metric)
}

// SetCounterMetric indicates an expected call of SetCounterMetric.
func (mr *MockIRepositoryMockRecorder) SetCounterMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCounterMetric", reflect.TypeOf((*MockIRepository)(nil).SetCounterMetric), metric)
}

// SetGaugeMetric mocks base method.
func (m *MockIRepository) SetGaugeMetric(metric models.Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGaugeMetric", metric)
}

// SetGaugeMetric indicates an expected call of SetGaugeMetric.
func (mr *MockIRepositoryMockRecorder) SetGaugeMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGaugeMetric", reflect.TypeOf((*MockIRepository)(nil).SetGaugeMetric), metric)
}
